server:
  port: ${PORT:9000}
  servlet:
    context-path: /api
  http2:
    enabled: true

#*******************************************************************************
#                           Spring configuration
#******************************************************************************/
spring:
  messages:
    basename: messages,api-messages,ValidationMessages
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  freemarker:
    charset: UTF-8
    content-type: text/html
    template-loader-path: classpath:/jp/afterfit/energy/mail/templates/

  #*******************************************************************************
  #                           Config Data source
  #******************************************************************************/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      # Optimize max connection pool: amount = ((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 10


#*******************************************************************************
#                           Config mybatis
#******************************************************************************/
mybatis:
  check-config-location: true
  mapper-locations: classpath*:ko/alliex/energy/persistence/dao/**/*.xml
  configuration:
    default-fetch-size: 100
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    cache-enabled: false
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial
    safe-row-bounds-enabled: false
    local-cache-scope: session
    jdbc-type-for-null: other
    lazy-load-trigger-methods: equals,clone,hashCode,toString
    aggressive-lazy-loading: false
# Mybatis paging
pagehelper:
  auto-dialect: true
  support-methods-arguments: true

# Actuator config
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: info, health, metrics, mappings
  metrics:
    export:
      atlas:
        enabled: false

### Logging settings
logging:
  file:
    path: ${LOG_PATH}

jwt:
  secret: ${JWT_SECRET}